# Generated by Django 4.0.6 on 2022-08-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_review_movies_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_at',
            field=models.DateField(auto_now=True),
        ),
    ]
