# Generated by Django 4.0.6 on 2022-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_review_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
